// <auto-generated />
namespace ConsoleAppEntityFW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createtabletblFilterNameGruops : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtabletblFilterNameGruops));
        
        string IMigrationMetadata.Id
        {
            get { return "201801291717305_create table tblFilterNameGruops"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
